# Add an environment: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

name: production deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: deploy
        # ...deployment-specific steps
