name: Greet Everyone
# This workflow is triggered manually.
on: 
  workflow_dispatch:


jobs:
  greet-users:
    # Job name is Greeting
    name: Greeting

    # This job runs on Linux (use [self-hosted, linux] for sel-hosted runner)
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Ubuntu the Octocat"
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }} on ${{ runner.name }} ${{ runner.os }}.'
